asm_linkage.o: asm_linkage.S
boot.o: boot.S multiboot.h x86_desc.h types.h
paging_asm.o: paging_asm.S
syscall_asm.o: syscall_asm.S
x86_desc.o: x86_desc.S x86_desc.h types.h
exceptions.o: exceptions.c exceptions.h lib.h types.h
file_system_driver.o: file_system_driver.c file_system_driver.h \
  devices/rtc.h devices/../types.h terminal.h types.h lib.h
idt.o: idt.c idt.h x86_desc.h types.h devices/keyboard.h devices/i8259.h \
  devices/../types.h devices/../lib.h devices/../types.h \
  devices/../x86_desc.h exceptions.h lib.h asm_linkage.h devices/rtc.h \
  paging.h syscall.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h debug.h tests.h \
  idt.h devices/keyboard.h devices/i8259.h devices/../types.h \
  devices/../lib.h devices/../x86_desc.h paging.h file_system_driver.h \
  devices/rtc.h terminal.h devices/i8259.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h types.h lib.h
syscall.o: syscall.c syscall.h paging.h types.h lib.h \
  file_system_driver.h devices/rtc.h devices/../types.h terminal.h
terminal.o: terminal.c terminal.h types.h lib.h file_system_driver.h \
  devices/rtc.h devices/../types.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h file_system_driver.h \
  devices/rtc.h devices/../types.h terminal.h
i8259.o: devices/i8259.c devices/i8259.h devices/../types.h \
  devices/../lib.h devices/../types.h devices/../x86_desc.h
keyboard.o: devices/keyboard.c devices/../lib.h devices/../types.h \
  devices/../x86_desc.h devices/keyboard.h devices/i8259.h \
  devices/../types.h devices/../terminal.h
rtc.o: devices/rtc.c devices/i8259.h devices/../types.h devices/../lib.h \
  devices/../types.h devices/../x86_desc.h devices/rtc.h
